### ISSUE TITLE
Support different domains for development and production

### ISSUE THREAD

**Issue by mats-claassen** [IDme/ID.me-WebVerify-SDK-iOS#5]
We want the requests of the SDK to (possibly) be made to different domains for development and production.

The production domain might be fixed but the user of the SDK should be able to specify the domain to use in development.

There are different approaches to do this. 
We need your feedback @sdownie

**Comment by m-revetria** [comment]
We may discuss about the use of a different domain for test: is it something private that shouldn't be accesible for the general public? Or conversely, is it something that we want to be used by any developer?

In addition, we *should* allow developers to have test and production environments in ID.me in order to test their own apps. This point can be a achieved in several ways, next are some ideas:

* Allow developers to create an application and enable a test mode for it, which will create some kind of a new application. This new test application is tied to the real application so you can easily move and configure properties between them. In the mobile app code, developers will use the client id for the real app in the production target and the client id of the test app in the test target.
* Additionally, it's common that developers create two app configurations in a 3rd party service in order to point their production and test targets to different data sources. So they will have to set the client id properly in each target.
* Allow developers to specify in some way if the app is running in "sandbox mode". I saw this pattern mainly implemented in payments solutions. So in the test target, developers should enable this test mode.

Thoughts?

**Comment by sdownie** [comment]
@mats-claassen @m-revetria Production is going to be the default environment for anyone using the SDK.  We're in a unique situation where we will use different domains.  Lets close this issue until we have a proper sandbox for mock app users can use to test.
