### ISSUE TITLE
The SDK should not replace null values with 'Unknown'

### ISSUE THREAD

**Issue by mats-claassen** [IDme/ID.me-WebVerify-SDK-iOS#9]
The response JSON data obtained from the backend is parsed and its `null` values are replaced with "Unknown". This should correspond to the user of the SDK and might not be desired in all cases.

**Comment by m-revetria** [comment]
@mats-claassen @sdownie: if we do this in that way (just avoiding to replace nulls with "Unknown"), we will get a `NSDictionary` with `NSNull` values instead of "Unknown" strings. Then, the user must check that each value in the result dictionary isn't a `NSNull` instance to prevent crashes (e.g. treating a `NSNull` as an `NSString`). **So this is a breaking change in the SDK**

Alternatively, we can remove NSNull instances from the dictionary, this way the user won't need to do anything else.

Thoughts?

**Comment by mats-claassen** [comment]
I agree that removing `NSNull` would be better. The current implementation does just remove `NSNull` for "Unknown" in the top level of the dictionary. It is OK for now as it is only used to get the user's profile but if this endpoint changes or it is used for another one then it should remove all `NSNull`, no matter how deep inside they are.
